### ISSUE TITLE
fail to run the demo

### ISSUE THREAD

**Issue by brfesuen** [drbenvincent/mcmc-utils-matlab#13]
OS is win 10, when I tried to run the demo, I encounter the following error:

No appropriate method, property, or field addParameter for class inputParser.

Error in mcmc/setPlotTheme (line 7)
p.addParameter('fontsize',14,@isscalar);

Error in demo (line 10)
mcmc.setPlotTheme('fontsize',16, 'linewidth',2)

I also got the same error when I run the demo 'run_me' of the 'delay-discounting-analysis' package.

So would you pls help me through this? Thanks so much!

**Comment by drbenvincent** [comment]
So the problem here is that the `addParameter` functionality was introduced in Matlab 2013b. See https://github.com/drbenvincent/delay-discounting-analysis/issues/203 for more.
